CREATE DATABASE IF NOT EXISTS iot_dht11 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE iot_dht11;

-- Dữ liệu cảm biến
CREATE TABLE IF NOT EXISTS sensor_data (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  temperature DECIMAL(5,2) NOT NULL,
  humidity DECIMAL(5,2) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Trạng thái điều khiển
CREATE TABLE IF NOT EXISTS device_state (
  id TINYINT PRIMARY KEY DEFAULT 1,
  fan TINYINT(1) NOT NULL DEFAULT 0,
  humidifier TINYINT(1) NOT NULL DEFAULT 0,
  led TINYINT(1) NOT NULL DEFAULT 0,
  buzzer TINYINT(1) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO device_state (id) VALUES (1) ON DUPLICATE KEY UPDATE id=id;

-- Ngưỡng cảnh báo
CREATE TABLE IF NOT EXISTS thresholds (
  id TINYINT PRIMARY KEY DEFAULT 1,
  temp_high DECIMAL(5,2) NOT NULL DEFAULT 35.00,
  hum_low DECIMAL(5,2) NOT NULL DEFAULT 40.00,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO thresholds (id) VALUES (1) ON DUPLICATE KEY UPDATE id=id;

-- Nhật ký cảnh báo
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  type VARCHAR(32) NOT NULL, -- TEMP_HIGH | HUM_LOW
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
